name: Check Links

on:
  pull_request:

concurrency:
  group: create-preview-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-groups

    - name: Install mint globally
      run: npm install -g mint@4.2.126

    - name: Check for broken links
      run: make broken-links
